language: c
dist: bionic
sudo: true
before_install: 
  - sudo apt-get update && sudo apt install -y nasm mtools curl build-essential libmpfr6 libfl2 doxygen
script:
  - source ./travis_scripts/download_dependecies.sh
  - ./configure.sh -w $TRAVIS_BUILD_DIR -t 1
  - ls
  - ./scripts/build.sh
  - doxygen Doxyfile
  - touch docs/html/.nojekyll
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $GH_REPO_TOKEN
    on:
      branch: develop
  - provider: releases
    skip_cleanup: true
    api_key: $GH_REPO_TOKEN
    file_glob: true
    file:
      - "build/floppy.img"
    on:
      tags: true
      branch: master